services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 19132:19132/udp
    depends_on:
      - bedrock-server

  bedrock-server:
    build:
      context: .
    volumes:
      - ./server:/server
    command: ./bedrock_server
    stdin_open: true
    tty: true
